export const serviceOptions = [
  "Limpeza doméstica",
  "Cozinha",
  "Cuidados com crianças",
  "Cuidados com idosos",
  "Jardinagem",
  "Motorista",
  "Segurança",
  "Manutenção",
  "Electricista",
  "Canalizador",
  "Pintor",
  "Carpinteiro",
  "Decorador",
  "Cabeleireiro",
  "Manicure",
  "Massagista",
  "Professor particular",
  "Tradutor",
  "Organizador de eventos",
  "Fotógrafo",
  "Técnico de informática",
  "Reparação de electrodomésticos",
  "Lavandaria",
  "Passadoria",
  "Administração",
  "Suporte técnico",
  "Gestão da plataforma",
  "Outros"
];